// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDapkO6LqYawyD3PtyXJp4qcrYzgOZsIEo',
    appId: '1:977743006223:web:6a65c8d5affb293c00f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    authDomain: 'newotp-60ee9.firebaseapp.com',
    storageBucket: 'newotp-60ee9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM6suH9aTSJ8U7bDFiv9cmkh-IzSGT_iE',
    appId: '1:977743006223:android:c05539a83608df9f00f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    storageBucket: 'newotp-60ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOd-KqahjNKvlUNvneWyoc1ok5umJ5fEI',
    appId: '1:977743006223:ios:d4b2242f8cce548200f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    storageBucket: 'newotp-60ee9.appspot.com',
    iosBundleId: 'com.example.clinikx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOd-KqahjNKvlUNvneWyoc1ok5umJ5fEI',
    appId: '1:977743006223:ios:d4b2242f8cce548200f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    storageBucket: 'newotp-60ee9.appspot.com',
    iosBundleId: 'com.example.clinikx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDapkO6LqYawyD3PtyXJp4qcrYzgOZsIEo',
    appId: '1:977743006223:web:31bca3adb142a9dc00f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    authDomain: 'newotp-60ee9.firebaseapp.com',
    storageBucket: 'newotp-60ee9.appspot.com',
  );
}
